spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
    data:
      source:
        init: true